### ISSUE TITLE
Unhandled Exception: No extractor found.

### ISSUE THREAD

**Issue by zacharisharris** [timrijckaert/raywenderlich_offline_downloader#2]
Hey there @timrijckaert , I am having a problem with the tool.
I have successfully downloaded some courses but for some others I always get this error:

`Found cached token for xxxx@gmail.com: 
{TOKEN GOES HERE}
Unhandled exception:
No extractor found which can extract metadata information for: https://www.raywenderlich.com/ios/paths/iossoftware
#0      RaywenderlichMetaDownloader._extractMetadata.<anonymous closure> (package:raywenderlich_offline_downloader/src/raywenderlich_offline_downloader.dart:66)
#1      Future.forEach.<anonymous closure> (dart:async/future.dart:508)
#2      Future.doWhile.<anonymous closure> (dart:async/future.dart:550)
#3      _RootZone.runUnaryGuarded (dart:async/zone.dart:1384)
#4      _RootZone.bindUnaryCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1423)
#5      Future.doWhile (dart:async/future.dart:566)
#6      Future.forEach (dart:async/future.dart:506)
#7      RaywenderlichMetaDownloader._extractMetadata (package:raywenderlich_offline_downloader/src/raywenderlich_offline_downloader.dart:59)
<asynchronous suspension>`

Any ways to solve this?

**Edit: This was for a learning path, but have gotten the same error with single courses.**

**Comment by timrijckaert** [comment]
I'll take a look, but I might be too strict in which urls I allow to download.
I'll check if I can expand on it.

**Comment by zacharisharris** [comment]
Please do, the tool is amazing.
Thank you again for taking the time for this :)

**Comment by timrijckaert** [comment]
Should be fixed 🤓

**Comment by zacharisharris** [comment]
It was indeed fixed but just for learning paths!
Though the same bug still persists for some other URLs I tried such as those:

https://www.raywenderlich.com/11590969-wwdc-2020-widgets
https://www.raywenderlich.com/12920765-wwdc-2020-screencasts
https://www.raywenderlich.com/4289-mastering-git

Initially I thought it might be a PRO error (which I am subscribed to) but I have downloaded other both PRO & non-PRO.
It must be a URL thing.
Please take a look at it if you have the time! 😇

**Comment by timrijckaert** [comment]
You are absolutely correct.
I changed it :)

Feel free to close the issue if it has resolved your issue.

**Comment by zacharisharris** [comment]
I'm afraid the error still persists. Now, I was able to download the WWDC 2020 Widgets video but the other two have problems such as:
https://www.raywenderlich.com/12920765-wwdc-2020-screencasts (downloads only 1 video file that is also from an irrelevant course)
 https://www.raywenderlich.com/4289-mastering-git (Here the error is the same as the original)

**Comment by timrijckaert** [comment]
Try again 👍 
I did however deprecate the learning paths urls since it was kind of messing with the flow

**Comment by zacharisharris** [comment]
Thank you very much! It seems to be working correctly now.
I'll go ahead and close the issue.

**Comment by timrijckaert** [comment]
Thanks it helped me to validate a few cases and improve the flow.
